[[blis]]
arch = "aarch64"
git-tree-sha1 = "01162061b3ba2a37377ec7e34de43e6559319a80"
os = "macos"

    [[blis.download]]
    sha256 = "c94ea54cc2c345112d0d0183c3c14146e8271cacc2b2a68ecb7a6b18cfd09e8c"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "363aa7d306a677eb3d5843e012b22dad7696f324"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "df5755db9259924cbae04b2a230a9f708cf73411556b7d2036a65dbd59c32e7e"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94dd45d1e64cde3d6d6eab1a904a8271b6fc3567"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "0bcc233adbdec5721f6d6e040174831f73f99e915e7951a4ac62d49d9750c4ba"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "3d9c1a6f0bd9ed317a031702dc47068a05ac7a9c"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "3384399b87eb5fec8bf57ed405b96770501fb2b9682bdf0b109b2569f6ed30f2"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "75945dba884d9f17e393fa89a376d976a1f2dfff"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "d66f874a4b16649f6a7516a75dc83d17a1f9f43aad3496970f07133c201ca0a3"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "12366ef0e4b7371e280a8753ad550f0590ebdb85"
os = "freebsd"

    [[blis.download]]
    sha256 = "1d11d27e70902eddb63751baae21b1d6f45efdf8a5ba6ebc32c68d9804aaa52e"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "b94feb85aa8616a3c8039bbf555a2d0b8ccf9942"
os = "windows"

    [[blis.download]]
    sha256 = "f3edf9e198fc0ecc5a16bfe0fcd63ef6f5ba4f379f5cfae85c7c0ecc64a1c646"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+4/blis.v0.9.0.x86_64-w64-mingw32.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "257a4bbeeb9250bf37949c49cb14ce7ac0c478d2"
os = "macos"

    [[blis.download]]
    sha256 = "486b29a4072d7fb09d1627cfddd13b110d70746eedd0954ac684aaf7c21ac5cb"
    url = "https://github.com/jd-foster/blis_jll.jl/releases/download/blis-v1.0.0+0/blis.v1.0.0.x86_64-apple-darwin.tar.gz"
