[[blis]]
arch = "aarch64"
git-tree-sha1 = "3531c1956dab8b13d738ae0dbe4c3ac033d4ad68"
os = "macos"

    [[blis.download]]
    sha256 = "74d75317d0e2e8c52ca5571b87dae4766d1e873adec89b4edbc6e869ca178207"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.aarch64-apple-darwin.tar.gz"
[[blis]]
arch = "aarch64"
git-tree-sha1 = "d13e5f05e0784c1cae74b455e80ffc4f94372629"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "0109d54f2916e70fd27e096136434aca9b90201e96463984fa6903ceff04dd76"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.aarch64-linux-gnu.tar.gz"
[[blis]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "82f79d6e721ffdac4fd30a9196d346845907f057"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "2c353746808f7d43defaf2eb7099de0ebe1f35e2b57f1709b219d3ea9ec5bde9"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "9848e9b9a0ca232e29efe3be25c1059dfebf03c6"
os = "macos"

    [[blis.download]]
    sha256 = "efddba41a547f3931f2e07575b018e56c2bb08dea99ccdb63a1c186f91264126"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.x86_64-apple-darwin.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "6908daa58e00fa4a08ae4cab660690ee5b9d4630"
libc = "glibc"
os = "linux"

    [[blis.download]]
    sha256 = "2dadc0d4d54e5faabb6ccb1f76c4e5540239fd7abfc1fceeee695ebd4ca0ec4d"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.x86_64-linux-gnu.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "5c53e0358223da220f6a277ff1ac21e9b21c4881"
libc = "musl"
os = "linux"

    [[blis.download]]
    sha256 = "0a3eef8e28f59df09bf331a85baa94ae0da6a613afe53d88732a1b9e0e1bbf3b"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.x86_64-linux-musl.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "714abd0bc9a3fac36ae3fdd25befdae23bdbcb9b"
os = "freebsd"

    [[blis.download]]
    sha256 = "76c92436a24840ddfd57ff984c6ce4159041dfd2af8b3e90baef335474ba01c6"
    url = "https://github.com/JuliaBinaryWrappers/blis_jll.jl/releases/download/blis-v0.9.0+1/blis.v0.9.0.x86_64-unknown-freebsd.tar.gz"
[[blis]]
arch = "x86_64"
git-tree-sha1 = "bb9fc06013b6d330fea4019af48ef1fccf2f80bf"
os = "windows"

    [[blis.download]]
    sha256 = "ec157a169bd13cc5f7b2f3f7a2e268d31da2e5beeb93af5b7b6205513f4c8062"
    url = "https://github.com/jd-foster/blis_jll.jl/releases/download/blis-v0.9.0+2/blis.v0.9.0.x86_64-w64-mingw32.tar.gz"
